### ISSUE TITLE
versioning for container images

### ISSUE THREAD

**Issue by Marethyu9999** [queerzard/CampusOnSpring#4]
so that we don't *"accidentally"* do something irrevertable....

**Comment by queerzard** [comment]
no shit sherlock

**Comment by Marethyu9999** [comment]
```yaml
name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current version
        id: get-version
        run: echo "::set-output name=version::$(git describe --tags --abbrev=0)"
      - name: Build & Push the Docker image
        run: |
          docker login --username queerzard --password ${{ secrets.gh_pat }} ghcr.io 
          docker build . --tag ghcr.io/queerzard/campusonspring:${{ steps.get-version.outputs.version }}
          docker push ghcr.io/queerzard/campusonspring:${{ steps.get-version.outputs.version }}
          docker tag ghcr.io/queerzard/campusonspring:${{ steps.get-version.outputs.version }} ghcr.io/queerzard/campusonspring:latest
          docker push ghcr.io/queerzard/campusonspring:latest
          
```
